<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.9">
  <POU Name="MAIN" Id="{57f19cc2-6624-4d85-bf79-2cb18e725034}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR

END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[
P_TextModeRead();

P_TextModeWrite();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="4" Count="3" />
    </LineIds>
  </POU>
</TcPlcObject>